apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: re3bbyiru-nodejs 
  janus-idp.io/tekton: re3bbyiru-nodejs
  backstage.io/kubernetes-id: re3bbyiru-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: re3bbyiru-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml